### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by photogeen** [nutritionfactsorg/daily-dozen-ios#32]
Hi, here in Germany many older people do not speak english. This app fits perfect for any age but there is this language barrier. 

Is it possible to add language support? I‘m not a coder but would contribute the translation for german.

cheers
eugene

**Comment by marc-medley** [comment]
@photogeen Thanks for the inquiry about `daily-dozen-ios` language support. Here is the current status:

**Daily Dozen iOS Language Support**

The current `daily-dozen-ios` release does not support any language localization. The `daily-dozen-ios` code base is in the process of being updated so that international languages can be added.  Once the language localization infracture is in place, then German would be one of the first languages to be added. 

Note that a release date for Daily Dozen iOS language support with a German translation is still to be determined.

**Existing Android German Translation**

The current released German translation for mobile devices can be viewed in the [`daily-dozen-android` repository](https://github.com/nutritionfactsorg/daily-dozen-android/blob/master/app/src/main/res/values-de/strings.xml).

**Volunteer Translator Team**

Here is a link for how to get involved with [NutritionFacts.org Volunteer Translator Team](https://nutritionfacts.org/volunteer/), if you would like help with current and future translation efforts.

**Comment by raphaelzulliger** [comment]
> The current `daily-dozen-ios` release does not support any language localization. The `daily-dozen-ios` code base is in the process of being updated so that international languages can be added. Once the language localization infracture is in place, then German would be one of the first languages to be added.

Is this still true? I can see some Spanish translations here: https://github.com/nutritionfactsorg/daily-dozen-ios/tree/master/DailyDozen/DailyDozen/App/Texts/LocalStrings/es.lproj. Are these just preliminarily there (i.e. not in use/inactive)?

**Comment by marc-medley** [comment]
@raphaelzulliger The `daily-dozen-ios` does supports localization since version 3.2.x. with Spanish being the first language added in version 3.2.1.

The localization coordination for both Android and iOS has been migrated to [nutritionfactsorg/daily-dozen-localization](https://github.com/nutritionfactsorg/daily-dozen-localization).

The localizations are going through translation and/or review by human translators. Please see `daily-dozen-localization` for more details.

**Comment by marc-medley** [comment]
@photogeen @raphaelzulliger As FYI, [iOS Daily Dozen with German translation](https://apps.apple.com/de/app/dr-gregers-daily-dozen/id1060700802) has been released.

If you find any translation issues, these can be reported as a [nutritionfactsorg/daily-dozen-localization/issue](https://github.com/nutritionfactsorg/daily-dozen-localization/issues). The `nutritionfactsorg/daily-dozen-localization` repository is used coordinate the translations for both the Daily Dozen for the Android and Apple devices. If you find a non-translation issue with the Apple iOS application itself, then that issue can be reported here to this `daily-dozen-ios` repository.
