### ISSUE TITLE
German translation for iOS app

### ISSUE THREAD

**Issue by mastergago** [nutritionfactsorg/daily-dozen-ios#58]
Hi,

I would like to translate the texts in the iOS app into German. I have no experience in using GitHub.  

How can I contribute?

Thanks in advance!

**Comment by marc-medley** [comment]
@mastergago iOS Daily Dozen version 3.2.11 includes the addition of German and several other languages. At this moment, version 3.2.11 is currently in Apple's App Store review process for a general global release, so this is advanced information.

Please see the [nutritionfactsorg/daily-dozen-localization](https://github.com/nutritionfactsorg/daily-dozen-localization) repository for current information.  The `daily-dozen-localization` repository is where the translations are coordinated for both the Android and Apple Daily Dozen applications.

If you find any translation issues, these can be reported as a [nutritionfactsorg/daily-dozen-localization/issue](https://github.com/nutritionfactsorg/daily-dozen-localization/issues). If you find a non-translation issue with the Apple iOS application itself, then that issue can be reported here to the `daily-dozen-ios` repository.

Closing this issue since a German version is in the process of being release, and the translations have moved to `daily-dozen-localization`.

**Comment by marc-medley** [comment]
@mastergago As FYI, [iOS Daily Dozen with German translation](https://apps.apple.com/de/app/dr-gregers-daily-dozen/id1060700802) has been released in the App Store.
