### ISSUE TITLE
[Help Wanted][Discussion] Apple Watch Integration

### ISSUE THREAD

**Issue by christirichards** [nutritionfactsorg/daily-dozen-ios#7]
We are looking for anyone that would like to tackle the creation of an Apple Watch integration for the Daily Dozen app. Please contact me at [christi@nutritionfacts.org](mailto:christi@nutritionfacts.org) if you're interested in getting this started or post any questions that you have below.  I'm also available on our private Slack [#development](https://nutritionfacts.slack.com/messages/development/) channel, please email me for an invite.

**Comment by andrewjrangel** [comment]
Are you still looking for help with the Apple Watch integration?

**Comment by marc-medley** [comment]
Hi @andrewjrangel . Since this issue was created in 2016, Swift has evolved such that an "Apple Watch integration" approach has been superseded by a unified `SwiftUI App` code base approach across multiple Apple platforms (iOS, watchOS, tvOS, iPadOS and macOS).

In the transition from v2 to v3, I've been cleaning up a number of underlying issues, structures and processes in a way that also prepares for a transition from Storyboards to SwiftUI. 

_So, the current iOS work-in-progress is also a watchOS work-in-progress_. As such, I will be closing this particular "Apple Watch integration" issue for now.

That said, if you wish to get involved with development, the best onboarding for the near term would be to build, test and use the latest code base of the app. Let us know your findings, feedback, etc. And then, we can go forward from there.

---

The [WWDC 2020 Session 10041 "What's new in SwiftUI"](https://developer.apple.com/videos/play/wwdc2020/10041) shows how a common SwiftUI App code base can be used for iOS, watchOS, tvOS, iPadOS, and macOS.  The particular SwiftUI elements presented include `App`. `Scene`, and `WindowGroup`. 

_Starting at 02:00…_

> `WindowGroup` is a powerful example of how scenes in SwiftUI can provide intelligent multi-platform functionality out-of-the box. In our iOS app, `WindowGroup` is creating and managing a single full screen window for our application. But **_the same code can also run on WatchOS_**, also managing a single full screen window.
>
> **_Of course our WatchOS app looks different than our iOS app. But, the core app structure is the same on both platforms._**
>
> _... in fact my app will also work on tvOS.
> ... and on the iPad too. ... this also extends to macOS._

![iOS](https://user-images.githubusercontent.com/15098151/85692284-21fa1100-b68a-11ea-8349-6a8052648530.jpg)

![watchOS](https://user-images.githubusercontent.com/15098151/85692325-29b9b580-b68a-11ea-801e-8737ce76db3b.jpg)

![tvOS](https://user-images.githubusercontent.com/15098151/85692429-3b9b5880-b68a-11ea-8445-d3fb09bccec9.jpg)

![iPadOS](https://user-images.githubusercontent.com/15098151/85692458-42c26680-b68a-11ea-8318-190c4cfd8e8b.jpg)

![macOS](https://user-images.githubusercontent.com/15098151/85692480-4950de00-b68a-11ea-84d7-0eeebe2f795f.jpg)
